// Authorization
export const AUTH_LOGIN_USER_REQUEST = 'AUTH_LOGIN_USER_REQUEST';
export const AUTH_LOGIN_USER_FAILURE = 'AUTH_LOGIN_USER_FAILURE';
export const AUTH_LOGIN_USER_SUCCESS = 'AUTH_LOGIN_USER_SUCCESS';
export const AUTH_LOGOUT_USER = 'AUTH_LOGOUT_USER';

// API
export const DATA_FETCH_PROTECTED_DATA_REQUEST = 'DATA_FETCH_PROTECTED_DATA_REQUEST';
export const DATA_RECEIVE_PROTECTED_DATA = 'DATA_RECEIVE_PROTECTED_DATA';

// App
export const GLOBAL_APP_NAME = 'BBytes';
export const GLOBAL_DESCRIP = 'Shopping List Generator';

// Shopping List
export const SL_FETCH_INGREDIENTS_FAILURE = 'SL_FETCH_INGREDIENTS_FAILURE';
export const SL_FETCH_INGREDIENTS_REQUEST = 'SL_FETCH_INGREDIENTS_REQUEST';
export const SL_FETCH_INGREDIENTS_SUCCESS = 'SL_FETCH_INGREDIENTS_REQUEST';

